id: hl7.fhir.us.msh
canonical: http://hl7.org/fhir/us/military-service
version: 1.0.1
name: military-service
title: "HL7 FHIR Implementation Guide: Military Service History and Status
  Release 1 - US Realm | STU1"
status: active
publisher:
  name: HL7 Cross-Group Projects WG
  url: https://confluence.hl7.org/display/CGP/Cross-Group+Projects+Home
  email: cgp@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: Military Service History and STatus is an implementation guide for veteran status and history verification and confirmation.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.us.odh: 1.0.0
  hl7.terminology: 2.1.0
parameters:
  show-inherited-invariants: true
copyrightYear: 2020+
releaseLabel: STU1
pages:
  index.md:
    title: Home
  conformance-general.md:
    title: Conformance Expectations
  conformance-profiles.md:
    title: Profile Conformance
  terminology.md:
    title: Terminology
  examples.md:
    title:  Examples
  change_log.md:
    title: Change log
menu:
  Home: index.html
  Conformance:
    General Expectations: conformance-general.html
    Profile Conformance: conformance-profiles.html
  Terminology: terminology.html
  Example: examples.html
  All Artifacts: artifacts.html
  Change Log: change_log.html
  History: http://hl7.org/fhir/us/msh/history.html
