id: hl7.fhir.us.military-service
canonical: http://hl7.org/fhir/us/military-service
version: 0.2.0
name: military-service
title: "HL7 FHIR Implementation Guide: Military Service History and Status
  Release 1 - US Realm | STU1 Ballot"
status: active
publisher:
   name: Cross Group Projects WG
   url: http://www.hl7.org/Special/committees/cgp
   email: cgp@lists.hl7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: Military Service History and Status is an implementation guide for veteran status and history verification and confirmation.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.us.odh: 1.2.0
  hl7.terminology: 2.1.0
parameters:
  show-inherited-invariants: true
copyrightYear: 2020+
releaseLabel: STU1 Ballot
pages:
  index.md:
    title: Home
  veteran.md:
    title: Veteran
  militaryhistory.md:
    title: Military History
  conformance-general.md:
    title: Conformance Expectations
  conformance-profiles.md:
    title: Profile Conformance
  terminology.md:
    title: Terminology
  examples.md:
    title:  Examples
  change_log.md:
    title: Change log
menu:
  Home: index.html
  Content by Group:
     Veteran: veteran.html
     Military History: militaryhistory.html
  Conformance:
    General Expectations: conformance-general.html
    Profile Conformance: conformance-profiles.html
  Terminology: terminology.html
  Example: examples.html
  All Artifacts: artifacts.html
  Change Log: change_log.html
  History: http://hl7.org/fhir/us/military-service/history.html


  # for ODH/PHINVADS value sets, specify dependencies: http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads version 0.12.0
